apiVersion: v1
data:
  ### Aqua database password. Defaults to "password". Please change the same if needed.
  password: cGFzc3dvcmQK
kind: Secret
metadata:
  annotations:
    description: Aqua database password secret
  labels:
    deployedby: aqua-yaml
  name: aqua-db
  namespace: aqua
type: Opaque
# ---
# The following certs is used to provide secure HTTPS communication between all the Aqua components
# If the certs are self signed the same needs to be mounted into scanner container for secure HTTPS communication.
# apiVersion: v1
# data:
#  aqua.key:  ## Input Needed  -  base64 value of Private cert ##
#  aqua.crt:  ## Input Needed  -  base64 value of Public cert ##
# kind: Secret
# metadata:
#   annotations:
#     description: Aqua SSL certificates
#   labels:
#     deployedby: aqua-yaml
#   name: aqua-ssl
#   namespace: aqua
# type: Opaque
# ---
# Use the following kubectl command to create registry secret to authenticate during image pull
## kubectl create secret docker-registry aqua-registry --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email> -n aqua
# If you already have the credentials already configured in .docker/config.json file use the following secret block to add docker pull secrets
# apiVersion: v1
# data:
#   .dockerconfigjson: ## Input Needed ##
# kind: Secret
# metadata:
#   annotations:
#     description: Secret for pulling Aqua images
#   labels:
#     deployedby: aqua-yaml
#   name: aqua-registry
#   namespace: aqua
# type: kubernetes.io/dockerconfigjson
# ---
# # Use the following secret block to add admin password and license as env variable. If not set the admin will be prompted for the same up on initial login.
# apiVersion: v1
# data:
#   ### Aqua admin password
#   ADMIN_PASSWORD: ## Input Needed ##
#   LICENSE_TOKEN: ## Input Needed ##
# kind: Secret
# metadata:
#   annotations:
#     description: Aqua administrator password and License tokens
#   labels:
#     deployedby: aqua-yaml
#   name: aqua-csp-server-secret
#   namespace: aqua
# type: Opaque