---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aqua-scanner
spec:
  template:
    metadata:
      labels:
        app: aqua-scanner
      name: aqua-scanner
    spec:
      serviceAccount: aqua
      containers:
      - name: aqua-scanner
        image: aquasec/scanner-cli:4.0
        args: ["daemon", "--user", "<user>", "--password", "<password>", "--host", "http://aqua-web:8080"]
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket-mount
        ports:
        - containerPort: 8080
      volumes:
        - name: docker-socket-mount
          hostPath:
            path: /var/run/docker.sock