version: '3.8'
services:
  aqua-enforcer-deployment:
    image:  registry.aquasec.com/enforcer:2022.4
    container_name: aqua-enforcer
    env_file:
      - aqua-enforcer.env
    restart: always
    pid: "host"
    privileged: true
    volumes:
      - /var/run:/var/run
      - /dev:/dev
      - /opt/aquasec:/host/opt/aquasec:ro
      - /opt/aquasec/tmp:/opt/aquasec/tmp
      - /opt/aquasec/audit:/opt/aquasec/audit
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
