---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqua-db
  labels:
    app: aqua-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-db
  template:
    metadata:
      labels:
        app: aqua-db
      name: aqua-db
    spec:
      securityContext:
        fsGroup: 70
        fsUser: 70
      serviceAccount: aqua-sa
      restartPolicy: Always
      containers:
      - name: aqua-db
        image: registry.aquasec.com/database:4.6
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: aqua-db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db
        ports:
        - containerPort: 5432
          protocol: TCP
      volumes:
      - name: postgres-db
        # To use persistentVolumeClaim to store DB content, comment out
        # deployment.spec.template.spec.volumes.hostPath field as applicable,
        # uncomment deployment.spec.template.spec.volumes.persistentVolumeClaim field
        persistentVolumeClaim:
          claimName: aqua-db-pvc
        # To use hostPath to store DB content, comment out
        # deployment.spec.template.spec.volumes.persistentVolumeClaim field as applicable,
        # uncomment deployment.spec.template.spec.volumes.hostPath field
        #hostPath:
        #  path: /var/lib/aqua/db
