version: '3.8'
services:
  aqua-db:
    image: registry.aquasec.com/database:2022.4.13
    ports:
      - "5432:5432"
    container_name: aquadb
    env_file:
        - aqua-db.env 
    volumes: 
      -  /var/lib/aqua-db/data:/var/lib/postgresql/data 
        
  aqua-web:
    image: registry.aquasec.com/console:2022.4.13
    ports:
      - "8080:8080"
      - "443:8443"
    container_name: aquaweb
    env_file:
      - aqua-web.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    
  aqua-gateway: 
    image: registry.aquasec.com/gateway:2022.4.13
    ports: 
      - "3622:3622"
      - "8443:8443"
    container_name: aqua-gateway
    env_file:
      - aqua-gateway.env
