apiVersion: v1
kind: PersistentVolume
metadata:
  name: aquadb-pv
  labels:
    app: aqua-csp
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/var/lib/aquadata/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aquadb-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: aquadb-pv
  selector:
    matchLabels:
      app: aqua-csp
---
apiVersion: v1
kind: Service
metadata:
  name: aqua-gateway
  labels:
    app: aqua-gateway
spec:
  ports:
    - port: 3622
  selector:
    app: aqua-csp
---
apiVersion: v1
kind: Service
metadata:
  name: aqua-web
  labels:
    app: aqua-web
spec:
  ports:
    - port: 8080
  selector:
    app: aqua-csp
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aqua-csp
spec:
  template:
    metadata:
      labels:
        app: aqua-csp
      name: aqua-csp
    spec:
      serviceAccount: aqua
      containers:
      - name: aqua-csp
        image: registry.aquasec.com/csp:4.0
        env:
          - name: BATCH_INSTALL_TOKEN
            value: AQUA_BATCH_TOKEN
          - name: BATCH_INSTALL_NAME
            value: AQUA_BATCH_AGENT
          - name: BATCH_INSTALL_GATEWAY
            value: "aqua-gateway:3622"
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: aquadb-data-mount
          - mountPath: /var/run/docker.sock
            name: docker-socket-mount
        ports:
        - containerPort: 8080
        - containerPort: 3622
      volumes:
        - name: docker-socket-mount
          hostPath:
            path: /var/run/docker.sock
        - name: aquadb-data-mount
          persistentVolumeClaim:
            claimName: aquadb-pvc