---
USERNAME: ""
PASSWORD: ""
ENFORCER_VERSION: ""
ENFORCER_MAJOR_VERSION: "2022.4"
TOKEN: ""
GATEWAY_ENDPOINT: ""
AQUA_TLS_VERIFY: "false"
AQUA_ROOT_CA: ""
AQUA_PUBLIC_KEY: ""
AQUA_PRIVATE_KEY: ""
INSTALL_PATH: "/opt"
ENFORCER_RUNC_DIRECTORY: "{{ INSTALL_PATH }}/aqua-runc"
ENFORCER_RUNC_FS_DIRECTORY: "{{ ENFORCER_RUNC_DIRECTORY }}/aqua-enforcer"
SYSTEMD_FOLDER: "/etc/systemd/system"
ENFORCER_SERVICE_FILE_NAME: "aqua-enforcer.service"
ENFORCER_SERVICE_TEMPLATE_FILE_NAME: "aqua-enforcer.template.service"
ENFORCER_SERVICE_TEMPLATE_FILE_NAME_OLD: "aqua-enforcer.template.old.service"
RUN_SCRIPT_FILE_NAME: "run.sh"
RUN_SCRIPT_TEMPLATE_FILE_NAME: "run.template.sh"
ENFORCER_SERVICE_SYSTEMD_FILE_PATH: "{{ SYSTEMD_FOLDER }}/{{ ENFORCER_SERVICE_FILE_NAME }}"
ENFORCER_RUNC_CONFIG_FILE_NAME: "config.json"
ENFORCER_RUNC_TAR_FILE_NAME: "aqua-host-enforcer.{{ ENFORCER_VERSION }}.tar"
ENFORCER_RUNC_AMD64_RPM_FILE_NAME: "aqua-vm-enforcer-{{ ENFORCER_VERSION }}.x86_64.rpm"
ENFORCER_RUNC_ARM64_RPM_FILE_NAME: "aqua-vm-enforcer-{{ ENFORCER_VERSION }}.aarch64.rpm"
ENFORCER_SELINUX_POLICY_FILE_NAME: "aquavme"
ENFORCER_DOWNLOAD_BASEURL: "https://download.aquasec.com/host-enforcer"
ROOT_CA_FILENAME: "{% if AQUA_ROOT_CA != None %}{{ AQUA_ROOT_CA | basename }}{% endif %}"
PUBLIC_KEY_FILENAME: "{% if AQUA_PUBLIC_KEY != None %}{{ AQUA_PUBLIC_KEY | basename }}{% endif %}"
PRIVATE_KEY_FILENAME: "{% if AQUA_PRIVATE_KEY != None %}{{ AQUA_PRIVATE_KEY | basename }}{% endif %}"
AQUA_ROOT_CA_PATH: "{% if AQUA_ROOT_CA != None %}/opt/aquasec/ssl/{{ ROOT_CA_FILENAME }}{% endif %}"
AQUA_PUBLIC_KEY_PATH: "{% if AQUA_PUBLIC_KEY != None %}/opt/aquasec/ssl/{{ PUBLIC_KEY_FILENAME }}{% endif %}"
AQUA_PRIVATE_KEY_PATH: "{% if AQUA_PRIVATE_KEY != None %}/opt/aquasec/ssl/{{ PRIVATE_KEY_FILENAME }}{% endif %}"
