# ---
# apiVersion: v1
# data:
#  # Please follow instruction in document to generate new SSL certs
#    server.key: ""
#    server.crt: ""
# kind: Secret
# metadata:
#   annotations:
#     description: Kube Enforcer SSL certificates to communicate with Kube API server
#   labels:
#     deployedby: aqua-yaml
#   name: aqua-kube-enforcer-certs
#   namespace: aqua
# type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    description: Aqua Enforcer token secret
  labels:
    deployedby: aqua-yaml
  name: aqua-kube-enforcer-token
  namespace: aqua
type: Opaque
data:
  ## In the Enforcers screen, edit the KubeEnforcer to get the token from the default KubeEnforcer group configuration. - Base64 encoded ##
  token: ""
